language: php

php:
  - 7.0
  - 7.1

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install php-pear
  - sudo apt-get install -y ghostscript
  - sudo pecl install imagick
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-source $PREFER_LOWEST

script:
  - phpunit
